### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by ChristianSchneeweiss** [ChristianSchneeweiss/Chat-txt-To-CSV#1]
Create a `requirements.txt` file for the used libraries

**Comment by NNTin** [comment]
https://github.com/ChristianSchneeweiss/Chat-txt-to-csv/pull/2

Regarding this pull request.

You can get a list of all currently installed libraries on your system with: `python -m pip freeze`.   
I would recommend this procedure to get a "proper" requirements.txt file.

```bash
# delete all dependencies
python -m pip freeze > requirements.txt
python -m pip uninstall -r requirements.txt

# install your dependencies for the project
python -m pip install <package name> [<more package names>]

# creating your requirements.txt
python -m pip freeze > requirements.txt
```

Bonus points if you are using venv. (Virtual environment for your python project. You probably have multiple python projects running with conflicting libraries. This one solves it.)

**Comment by ChristianSchneeweiss** [comment]
I do know about this commands. I still think this a beginner friendly issue for someone to create their first PR, therefore I would not want to create this by myself. 

#1 is exactly the PR I expected. Thank you.
